sudo: false
language: "python"
python:
    - "2.7"
script: "python -m unittest discover"
services:
    - "redis-server"
deploy:
  provider: "pypi"
  user: "honzajavorek"
  password: "..."
  on:
    python: "2.7"
    tags: true
    repo: "honzajavorek/redis-collections"
